### ISSUE TITLE
Multiline strings are not supported

### ISSUE THREAD

**Issue by dlsniper** [intellij-rust/intellij-toml#1]
Hi, please see this as an example: https://raw.githubusercontent.com/toml-lang/toml/master/examples/example-v0.4.0.toml

``` toml
[string.literal.multiline]

regex2 = '''I [dw]on't need \d{2} apples'''
lines  = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
```

**Comment by matklad** [comment]
Hi! 

Sorry for a long delay. We are currently busy building IntelliJ-Rust plugin, and improving TOML plugin is not our priority at the moment. We do plan to make an awesome TOML plugin in the long run though.

But contributions are welcome, and I will try to respond to PRs in a timely manner :)
