### ISSUE TITLE
Host in JetBrains Repository

### ISSUE THREAD

**Issue by johnthagen** [intellij-rust/intellij-toml#12]
@matklad Was the TOML plugin removed from the repository?
https://plugins.jetbrains.com/plugin/8195

I can't find it when browsing the Plugins from inside PyCharm 2016.2.3 on Windows or macOS, and it looks like there are no versions uploaded to this site?

Was this intentional?  It's really convenient to install this plugin with `intellij-rust` when working Rust code.

**Comment by johnthagen** [comment]
Oops, I had forgotten about the README instructions, my bad.  The plugin seems to work fine, is there any   reason it can't be put onto the main plugin site for greater exposure?

**Comment by Centaur** [comment]
It is not production ready yet, so the nightly channel is the right place to go.  

The better question is, why the toml plugin is only available for idea ultimate version? Which means the community edition is no more a full dev environment for rust.

**Comment by johnthagen** [comment]
@Centaur I thought it worked in PyCharm Community, but haven't tried out IDEA Community.

**Comment by matklad** [comment]
Development moved to https://github.com/intellij-rust/intellij-rust/tree/master/toml.

I've also publish the first version of the plugin to the main channel. It should work with any IDE.
