### ISSUE TITLE
Not working (installed, but like if it wasn't, no coloration, no settings)

### ISSUE THREAD

**Issue by Litarvan** [intellij-rust/intellij-toml#14]
I'm using IntelliJ IDEA 2016.3 but, even with the plugin :
![Plugin installed](https://i.gyazo.com/6ac0af81f4549fdb744d91d5be3eeb83.png)

It's like if it wasn't installed, no coloration, no TOML settings, and asking what kind of file it is when creating a .toml file...

![Example](https://i.gyazo.com/71545aba9cb3c58ec728278da45831a1.png)

**Comment by chriskrycho** [comment]
I'm seeing the same on the 2016.3 series (not sure if it was the same on the 2016.2 series; I've been on the EAPs for a while).

**Comment by matklad** [comment]
I guess I'll move this back within IntelliJ Rust codebase, because coordinating updates to the build script across two repositories is a pain, and I don't think this plugin has much usage outside of Rust. Is this correct, @dlsniper?

**Comment by Litarvan** [comment]
Toml wasn't written for Rust, i think it is always useful

**Comment by alepar** [comment]
I can confirm it stopped working once I upgraded to 2016.3 (was working fine on 2016.2)

Also, when I try to force 2016.3 to check the repository for plugins ("Check now" button in edit repository dialog), it will tell me that no plugins found.

Hopefully, just needs a version bump?

**Comment by dlsniper** [comment]
@matklad as @Litarvan already said, TOML is useful outside of Rust as well. Many in the Go community recommend it as a configuration language so I'm not sure what to say about this. You guys probably have better usage statistics than me.

**Comment by alepar** [comment]
Oh, I use this outside Rust too...

**Comment by matklad** [comment]
Ok, I guess I just need to pay more attention to this plugin! Alternatively, maybe I can have a cake and eat it two, and just keep "two" plugins in the same repository and with the same config?

**Comment by dlsniper** [comment]
@matklad as long as the plugin can be installed w/o the Rust part it doesn't matter for me where it comes from (and I guess it won't for any user).

**Comment by Litarvan** [comment]
Fixed myself, see https://github.com/intellij-rust/intellij-toml/pull/15

**Comment by Litarvan** [comment]
PR Merged, issue fixed !

**Comment by matklad** [comment]
So the development moved to https://github.com/intellij-rust/intellij-rust/tree/master/toml. 

I've also published a version to the default channel, so yo don't need to add plugin repository specially.

**Comment by alepar** [comment]
Cool, thank you very much, @matklad !
Just installed 2016.3 back and verified it works. Now intellij will even notify me that there's a plugin for *.toml files and offer to install it. Neat!
