### ISSUE TITLE
Support dotted keys

### ISSUE THREAD

**Issue by zh0uquan** [intellij-rust/intellij-toml#17]
According to [toml specification](https://github.com/toml-lang/toml), `Dotted keys are a sequence of bare or quoted keys joined with a dot. `, which is natively supported by toml. But when I use dots keys in the toml file, my PyCharm gives me an error highlight: `"=" expected, "." found`, Can we remove this error highlight? And is it an IDE related issue?

**Comment by matklad** [comment]
This repo has moved, closing in favor of https://github.com/intellij-rust/intellij-rust/issues/2610!
