### ISSUE TITLE
Publish plugin on nightly release channel

### ISSUE THREAD

**Issue by dlsniper** [intellij-rust/intellij-toml#3]
The [Go plugin](https://github.com/go-lang-plugin-org/go-lang-idea-plugin) takes advantage of the nightly / alpha release channels to release preview versios of the plugin.

Could this be released as a nightly build at least for now so that it can be installed easier than compiling it from sources? Thank you.

**Comment by matklad** [comment]
Fixed (for a while already actually :( )

https://github.com/intellij-rust/intellij-toml#installation

**Comment by matklad** [comment]
@dlsniper  FYI, I've published 0.2 version of TOML plugin,  which provides a stable PSI interface and reference contributors, so it's now possible to implement technology-specific features on top of it, see https://github.com/intellij-rust/intellij-rust/pull/1982 for an example.
